server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:mariadb://localhost:3306/yourDatabaseName
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver

